#!/usr/bin/env bash
# =============================================================================
# init-env.sh — Generate agent/.env from Terraform outputs.
#
# Run this ONCE after "terraform apply" completes.
# It reads every value from Terraform outputs so you never have to look them
# up manually or risk typos.
#
# Usage:
#   bash scripts/init-env.sh
#
# Prerequisites:
#   - terraform apply has completed successfully
#   - you are authenticated: gcloud auth application-default login
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
TF_DIR="$ROOT_DIR/iac"
ENV_FILE="$ROOT_DIR/agent/.env"

# ── Validate terraform state is present ──────────────────────────
if [ ! -f "$TF_DIR/terraform.tfstate" ]; then
  echo ""
  echo "ERROR: No terraform.tfstate found in $TF_DIR"
  echo "       Run 'terraform apply' inside the iac/ directory first."
  echo ""
  exit 1
fi

echo ""
echo "Reading Terraform outputs..."
echo ""

# ── Read all values from terraform outputs ───────────────────────
PROJECT_ID=$(terraform -chdir="$TF_DIR" output -raw project_id)
REGION=$(terraform -chdir="$TF_DIR" output -raw region)
CUSTOM_MCP_URL=$(terraform -chdir="$TF_DIR" output -raw custom_mcp_url)
EVIDENCE_BUCKET=$(terraform -chdir="$TF_DIR" output -raw evidence_bucket_name)
STAGING_BUCKET=$(terraform -chdir="$TF_DIR" output -raw staging_bucket_url)
SA_EMAIL=$(terraform -chdir="$TF_DIR" output -raw agent_service_account_email)

# ── Write agent/.env ─────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# =============================================================================
# agent/.env — Auto-generated by scripts/init-env.sh
# Generated : $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Source    : terraform outputs from iac/
#
# DO NOT edit this file manually — re-run scripts/init-env.sh to refresh.
# This file is gitignored and must not be committed.
# =============================================================================

# ── GCP Project ──────────────────────────────────────────────────
PROJECT_ID=${PROJECT_ID}
REGION=${REGION}

# ── Gemini model ─────────────────────────────────────────────────
GEMINI_MODEL=gemini-2.5-flash

# ── MCP endpoints ────────────────────────────────────────────────
# Custom MCP server deployed on Cloud Run (fallback when GKE Remote MCP
# does not return enough evidence)
K8S_MCP_URL=${CUSTOM_MCP_URL}

# Google-managed GKE Remote MCP — this URL is fixed, do not change it
GKE_REMOTE_MCP_URL=https://container.googleapis.com/mcp/read-only

# ── GCS buckets ──────────────────────────────────────────────────
# Evidence bucket name only (no gs:// prefix)
EVIDENCE_BUCKET=${EVIDENCE_BUCKET}

# Staging bucket URL (with gs:// prefix) — used by deploy_agent.py
STAGING_BUCKET=${STAGING_BUCKET}

# ── Agent service account ────────────────────────────────────────
AGENT_SERVICE_ACCOUNT=${SA_EMAIL}

# ── Agent Engine resource name ───────────────────────────────────
# Set this AFTER running: python deploy_agent.py
# Example: projects/YOUR-PROJECT-NUMBER/locations/us-central1/reasoningEngines/123456
# AGENT_RESOURCE_NAME=
EOF

# ── Print summary ────────────────────────────────────────────────
echo "agent/.env written successfully:"
echo ""
echo "  PROJECT_ID      : ${PROJECT_ID}"
echo "  REGION          : ${REGION}"
echo "  K8S_MCP_URL     : ${CUSTOM_MCP_URL}"
echo "  EVIDENCE_BUCKET : ${EVIDENCE_BUCKET}"
echo "  STAGING_BUCKET  : ${STAGING_BUCKET}"
echo "  SERVICE_ACCOUNT : ${SA_EMAIL}"
echo ""
echo "Next steps:"
echo "  1. Connect kubectl  : $(terraform -chdir="$TF_DIR" output -raw gke_connect_command)"
echo "  2. Test locally     : python run.py \"pod X is in OOMKilled\" --namespace test-incidents --pod X"
echo "  3. Deploy to AE     : python deploy_agent.py"
echo ""
